# Generated by Django 4.2.24 on 2025-09-24 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlowFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename", max_length=255, unique=True
                    ),
                ),
                (
                    "file_reference",
                    models.CharField(
                        help_text="File reference from ZHV header", max_length=50
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Import timestamp"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of records imported"
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow File",
                "verbose_name_plural": "Flow Files",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="MeterPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mpan",
                    models.CharField(
                        help_text="Meter Point Administration Number (13 digits)",
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mpan",
                                message="MPAN must be exactly 13 digits",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meter Point",
                "verbose_name_plural": "Meter Points",
                "ordering": ["mpan"],
                "indexes": [models.Index(fields=["mpan"], name="idx_meterpoint_mpan")],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Physical meter serial number", max_length=20
                    ),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("S", "Standard"),
                            ("C", "Credit"),
                            ("D", "Debit"),
                            ("P", "Prepayment"),
                            ("U", "Unknown"),
                        ],
                        default="S",
                        help_text="Type of meter (from 028 record)",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meter_point",
                    models.ForeignKey(
                        help_text="The meter point this meter is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="meter_readings.meterpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meter",
                "verbose_name_plural": "Meters",
                "ordering": ["meter_point__mpan", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_id",
                    models.CharField(
                        choices=[
                            ("S", "Standard"),
                            ("01", "Register 1"),
                            ("02", "Register 2"),
                            ("03", "Register 3"),
                            ("A1", "Advance 1"),
                            ("TO", "Total"),
                            ("DY", "Day"),
                            ("NT", "Night"),
                            ("WK", "Weekend"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "reading_date",
                    models.DateTimeField(
                        help_text="Date and time of the meter reading"
                    ),
                ),
                ("reading_value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reading_type", models.CharField(default="ACTUAL", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="meter_readings.flowfile",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="meter_readings.meter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading",
                "verbose_name_plural": "Readings",
                "ordering": ["-reading_date", "meter__meter_point__mpan"],
                "indexes": [
                    models.Index(fields=["reading_date"], name="idx_reading_date"),
                    models.Index(
                        fields=["meter", "reading_date"], name="idx_reading_meter_date"
                    ),
                    models.Index(fields=["flow_file"], name="idx_reading_flowfile"),
                ],
                "unique_together": {("meter", "register_id", "reading_date")},
            },
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(fields=["serial_number"], name="idx_meter_serial"),
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(
                fields=["meter_point", "serial_number"], name="idx_meter_mp_serial"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meter",
            unique_together={("meter_point", "serial_number")},
        ),
    ]
